---
- name: Converge
  hosts: all
  become: true

  vars:
    nodejs_install_npm_user: root
    verdaccio_systemd_state: stopped

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: verdaccio.verdaccio
